### ISSUE TITLE
 Build a usable browser with NSFW & Human detection feature

### ISSUE THREAD

**Issue by HMZahir** [AsilHQ/asil-android#53]
**Features**

- [ ] Blur the whole images.1.Gender model 2.NSFW
- [ ] Full settings integration — detection aggressiveness, blur strength. Show stats on detection.
- [ ] Implement KahfGuard API call to block users accessing KahfGuard-blocked pages
- Productionize browser for App Store launch
- Beta trial with users to get feedback on performance & reliability

**Acceptance Criteria:**
- The browser should have a built-in NSFW detection feature that can identify potentially inappropriate content (nudity, violence, etc.) on web pages.
- The browser should also have a human detection feature that can identify the presence of people in images and videos.
- Upon detecting NSFW and human content, the entire webpage or image/video should be blurred by default.
- Users should have the option to disable the NSFW and human detection features if desired.
- The browser should prioritize user privacy and avoid collecting any browsing data or personal information.

**Comment by tawfiq23** [comment]
[In this version](https://drive.google.com/file/d/1Gu7ggEdqTQU0C2sDwM_qQ8S6KfUcaoaH/view?usp=sharing), 3 on-device models are used to classify images.
1.⁠ ⁠Nsfw
2.⁠ ⁠⁠Google ML kit’s face detection model
3.⁠ ⁠⁠Gender detection

I tested the predictions on some newspaper sites. Didn’t check any nsfw sites. I found some false positive and false negative predictions for nsfw and gender detection. App’s performance needs to be improved a lot.

The Image processing flow is as follows 
<img width="842" alt="image" src="https://github.com/AsilHQ/asil-android/assets/62983493/9a9d95d9-07e8-493e-99e9-27d0b6eb5f60">
