### ISSUE TITLE
 Android developments and fix priorities for V1 

### ISSUE THREAD

**Issue by HMZahir** [AsilHQ/asil-android#55]
- [ ] Make an android browser into limited beta test stage. @tawfiq23 
- [x]  Remove the safe gaze icon. Keep the KahfGuard icon but show a combined settings screen for blocking sites and blur settings. @tawfiq23 
- [x]  Ship improved blur algorithm to reduce false positives and misses. @Tawfiq23 
- [x]  Fix the email address field blur problem. @alganzory  
- [ ]  Make a nice homepage like the desktop browser.
- [x]  Fix the BBC website not loading any image after two scrolls. @alganzory 
- [x]  Fix Zionist supporters getting blurred. Joe Biden, Elon musk, John Kirby. 
- [x]  Mutation observer implementation. @alganzory  
- [ ]  Fix YouTube not getting any image blurred. @alganzory  
- [x]  Don't blur small images like profile pictures in x.com. @alganzory 
- [x]  Remove VPN mode. Use private DNS over https feature in the browser (iOS,android). @tawfiq23 @cemsertkaya 
- [ ]  Add an icon on blurred images to unblur it. @alganzory 
- [x]  Google images not getting blurred.@alganzory @tawfiq23 
- [ ]  Every website shows me a notice that I can open this website in an app. @tawfiq23  
- [ ]  Add crash dump collector and send it to us for analysis. @tawfiq23 
- [ ] Optimized and reduced the size of the gender detection model. @rupak
- [x] Need to do some more experiments to see when the appeal is gone. if skin tone and body curves are gone and body parts not so distinguishable from the background @alganzory  
- [ ] Disable auto video play and animated gif play, unless clicked. This will avoid a lot of annoyance and stop automatic ad playing. @alganzory 
- [x] #48 
- [x] #49 
- [x] #50 
- [ ] #51  
- [ ] #52 
- [x] #53 
- [ ] #54 
- [x] #56 
- [ ] #58

**Comment by alganzory** [comment]
@HMZahir You can also assign me these two 

> * [x]   Fix the email address field blur problem.
> * [x]   Google images not getting blurred.

**Comment by HMZahir** [comment]
Need to improve the following items:

- [ ] Get latest browser codes and make our changes on top of them. @tawfiq23 
- [x] ⁠Implement the new monotone+blur solution using the common slider @alganzory 
- [x] Make the slider default to 80% blur level. The goal is to make sure the default experience removes the harm and satisfies user. @alganzory 
- [ ] Set private DNS using browser setting. @tawfiq23 
- [ ] Explore if kotlin/swift can read image files directly from browser cache. If not, sSend image byte from JS to Kotlin. @alganzory 
- [ ] Dobble Click to android @alganzory

**Comment by HMZahir** [comment]
- [x] Bug: when scrolling, if touch a blurred image while swiping,, the image  unblurs. 
The tap on blurred image needs to understand a tap vs swipe. @alganzory

**Comment by HMZahir** [comment]
- [x] Including Grayscale int he slider @alganzory 
- [x] Tap to unblur @alganzory 
- [x] JS bug fix @alganzory 
- [x] Replace tap to unblur with long press to unblur @alganzory 
- [ ] css filters change to replace grayscale @alganzory 
- [ ] Base64/caching @alganzory 
- [ ] Timer to auto unblur @alganzory

**Comment by HMZahir** [comment]
- [ ] Update kahf codebase @tawfiq23
